// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm0NB4Y4PZI5Xx6YPAqkt5PHOtAzcpAS8',
    appId: '1:720057292479:web:ca70bd631bbfcd8add180a',
    messagingSenderId: '720057292479',
    projectId: 'alab-a9de0',
    authDomain: 'alab-a9de0.firebaseapp.com',
    storageBucket: 'alab-a9de0.appspot.com',
    measurementId: 'G-T7XFHVSHG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoEU8CHFtoIIsVPb3t6vHrGxdRLFSpNIU',
    appId: '1:720057292479:android:14d8247627f76d9bdd180a',
    messagingSenderId: '720057292479',
    projectId: 'alab-a9de0',
    storageBucket: 'alab-a9de0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4xX-UmfcMiT6lEbvyoUfX5N2YdVqH2pg',
    appId: '1:720057292479:ios:64b891b8d0a653b5dd180a',
    messagingSenderId: '720057292479',
    projectId: 'alab-a9de0',
    storageBucket: 'alab-a9de0.appspot.com',
    iosBundleId: 'com.example.alab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4xX-UmfcMiT6lEbvyoUfX5N2YdVqH2pg',
    appId: '1:720057292479:ios:64b891b8d0a653b5dd180a',
    messagingSenderId: '720057292479',
    projectId: 'alab-a9de0',
    storageBucket: 'alab-a9de0.appspot.com',
    iosBundleId: 'com.example.alab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm0NB4Y4PZI5Xx6YPAqkt5PHOtAzcpAS8',
    appId: '1:720057292479:web:a35dbb87270977c5dd180a',
    messagingSenderId: '720057292479',
    projectId: 'alab-a9de0',
    authDomain: 'alab-a9de0.firebaseapp.com',
    storageBucket: 'alab-a9de0.appspot.com',
    measurementId: 'G-WBFM52KC1B',
  );
}
